#! /bin/sh

#Wordt sudo gebruikt? dit moet gechekt worden.
if [ ! $(sudo echo 0) ]; then exit; fi

#Is er een vriable aanwezig? zo niet dan geeft men een error message terug
if [ $# -ne 1 ]; then
    echo "No or too many parameters provided, you need to give us a subzone to create: zone "\""SUBZONE.sander-verbeken.sb.uclllabs.be"\"" { ..."
    exit 1
fi

#In named.conf.mrt-zones wordt een nieuwe zone geadd aan de hand van de variable naam die mee wordt gegeven
echo "zone "\""$1.sander-verbeken.sb.uclllabs.be"\"" {
	type master;
        file "\""/etc/bind/zones/db.$1.sander-verbeken.sb.uclllabs.be"\"";
};" >> /etc/bind/named.conf.mrt-zones

#Als in de mrt-zones dir nog geen zone file bestaat met deze naam dan wordt deze aangemaakt
touch /etc/bind/zones/db.$1.sander-verbeken.sb.uclllabs.be

#SOA record van deze zonefile aangemaakt en in de juiste zonefile gestopt
echo "\$TTL 300
@ IN SOA $1.sander-verbeken.sb.uclllabs.be. host.sander-verbeken.sb.uclllabs.be. (
5000 ; Serial
300 ; Refresh
300 ; Retry
3000 ; Expire
300) ; Default TTL

;SERIALNUMB=5000

; NAME SERVERS
@       IN      NS ns.sander-vebreken.sb.uclllabs.be.

" > /etc/bind/zones/db.$1.sander-verbeken.sb.uclllabs.be

#Men moet een ns record toevoegen voor delegatie, om deze veranderingen door te laten gaan moeten we uiteraard ook de serial number verhogen, anders worden veranderingen niet door gegeven.
TEMPSERIALNUMB=$(grep -Po '(?<=SERIALNUMB=).*' /etc/bind/zones/db.sander-verbeken.sb.uclllabs.be)
NEWSERIALNUMB=$((TEMPSERIALNUMB+1))
sed -i "s/$TEMPSERIALNUMB/$NEWSERIALNUMB/g" /etc/bind/zones/db.sander-verbeken.sb.uclllabs.be

#NS record toevoegen aan mijn al bestaande zone file (db.sander-verbeken)
echo "$1	IN	NS	ns" >> /etc/bind/zones/db.sander-verbeken.sb.uclllabs.be

#Nu dat alles is ingesteld en aangepast moeten we de service restarten om alle aanpassingen door te geven.
systemctl restart bind9.service
