#! /bin/sh

#is the user using sudo?
if [ ! $(sudo echo 0) ]; then exit; fi

#the command zorks only if the user has one argument, the domain
if [ $# -eq 1 ]; then
        echo "1 argument, good"

	cutteddomain="$(echo $1 | cut -d'.' -f1)"
	cuttedzone="$(echo $1 | cut -d'.' -f2)"
	#echo $cuttedzone

	if [ $cuttedzone = "sander-verbeken" ]; then
		file="db.sander-verbeken.sb.uclllabs.be"
		filewithzone="$cutteddomain.sander-verbeken.sb.uclllabs.be"
		vhost_name="$cutteddomain"
	else
		file="db.$cuttedzone.sander-verbeken.sb.uclllabs.be"
		filewithzone="$cutteddomain.$cuttedzone.sander-verbeken.sb.uclllabs.be"
		vhost_name="$cutteddomain.$cuttedzone"
	fi
	#echo $file

	#First we will check if this domain exists in our dns configuration:
	if grep -w /etc/bind/zones/$file -e $cutteddomain -q
	then
		echo "subdomain $cutteddomain found in zone $cuttedzone"

		#so we found the domain now we can start making stuff

		#first make the directory in /var/www/...

		mkdir /var/www/$filewithzone

		#make the index.html file in the made directory and put the right text into it

		touch /var/www/$filewithzone/index.html
		echo "<html><p>welcome $vhost_name</p></html>" > /var/www/$filewithzone/index.html

		#now we need to make all the right files in the /etc/apache2/... folders

		#Lets make the .conf file in /etc/apache2/sites-available

		touch /etc/apache2/sites-available/$filewithzone.conf

echo "<VirtualHost *:80>
	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/$filewithzone

	ServerName sander-verbeken.sb.uclllabs.be
	ServerAlias $filewithzone

	ErrorLog \${APACHE_LOG_DIR}/$filewithzone.conf.error.log
	CustomLog \${APACHE_LOG_DIR}/$filewithzone.conf.access.log combined
</VirtualHost>" > /etc/apache2/sites-available/$filewithzone.conf

		#enable the site

		a2ensite $filewithzone.conf

		#Lets do a apache restart to let everything work

		systemctl restart apache2.service

		#Done :) (i hope) everything shouldve worked if the code reached it till here.

	else 	echo "didnt find this domain"
		exit 1
	fi

        exit 1
else 	echo "No arguments or too many were given, you only need one for this, no vhost was created"
	exit 1
fi
