#! /bin/sh

DBu='check'
DBp='rDEetGxq82DCE'
DBn='check'
DBt='log'




day=$(date +"%Y-%m-%d")
string='some string'
numb=1

until [ $numb -eq 81 ]; do
	echo "$string$numb"
	echo "$day"
	
	mysql --user=$DBu --password=$DBp $DBn -e "INSERT INTO $DBt (date,text) VALUES ('$day', '$string$numb')"
	numb=$(( $numb + 1 ))
done
